# Generated by Django 3.2.9 on 2021-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('request_type', models.CharField(max_length=50)),
                ('request_body', models.JSONField()),
                ('request_url', models.TextField()),
                ('request_success', models.BooleanField(default=False)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
