# Generated by Django 3.2.9 on 2021-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='0C3876E9F74A47D', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
