# Generated by Django 3.2.9 on 2021-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(auto_created=True, default='A399D0A28C8B4B9', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='D4F2A36523F3484', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
