# Generated by Django 3.2.9 on 2021-11-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(auto_created=True, default='D7E5592A93994A3', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='CFE629C3102F458', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
    ]
